In [1]:
import os
import re
import csv
import pandas as pd

In [4]:
df_1 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\cleaned_txt\final_cleaned\bab_cleaned\unknown_bab.csv")
df_2 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 1\cleaned_txt\final_cleaned\bab_cleaned\unknown_bab.csv")
df_3 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 2\cleaned_txt\final_cleaned\bab_cleaned\unknown_bab.csv")
df_4 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 3\cleaned_txt\final_cleaned\bab_cleaned\unknown_bab.csv")
df_5 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 4\cleaned_txt\final_cleaned\bab_cleaned\unknown_bab.csv")

In [5]:
unknown_combined = pd.concat([df_1, df_2, df_3, df_4, df_5], ignore_index=True)
unknown_combined

,judul,Pasal,Content
0,PERMEN_BUMN_No_1147_Tahun_2017_cleaned.txt,PASAL 1,Dalam Peraturan Menteri ini yang dimaksud deng...
1,PERMEN_BUMN_No_1147_Tahun_2017_cleaned.txt,PASAL 2,Prinsip -prinsip yang harus diperhatikan dala ...
2,PERMEN_BUMN_No_1147_Tahun_2017_cleaned.txt,PASAL 3,Kerja Sama dilakukan berdasarkan pada kemanf...
3,PERMEN_BUMN_No_1147_Tahun_2017_cleaned.txt,PASAL 4,Kerja Sama yang dilakukan oleh BUMN melipu ti...
4,PERMEN_BUMN_No_1147_Tahun_2017_cleaned.txt,PASAL 5,Kerja Sama dimana BUMN sebagai rekan kerja sa...
...,...,...,...
99,PERMEN_BUMN_No_46_Tahun_2018_Dirubah_812_2021_...,PASAL 10,Peraturan Menteri ini mulai berlaku pada tangg...
100,PERMEN_BUMN_No_812_Tahun_2021_Merubah_46_2018_...,PASAL 1,Dalam Peraturan Menteri ini yang dimaksud deng...
101,PERMEN_BUMN_No_812_Tahun_2021_Merubah_46_2018_...,PASAL 2,(1) Penyelenggara Negara wajib menyampaikan LH...
102,PERMEN_BUMN_No_812_Tahun_2021_Merubah_46_2018_...,PASAL 3,(1) Penyelenggara Negara sebagaimana dimaksud...
103,PERMEN_BUMN_No_812_Tahun_2021_Merubah_46_2018_...,PASAL 5,Penyampaian LHKPN dilaksanakan dengan cara me...

In [6]:
df_1 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\cleaned_txt\final_cleaned\bab_cleaned\known_bab.csv")
df_2 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 1\cleaned_txt\final_cleaned\bab_cleaned\known_bab.csv")
df_3 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 2\cleaned_txt\final_cleaned\bab_cleaned\known_bab.csv")
df_4 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 3\cleaned_txt\final_cleaned\bab_cleaned\known_bab.csv")
df_5 = pd.read_csv(r"C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\Perubahan 4\cleaned_txt\final_cleaned\bab_cleaned\known_bab.csv")

In [7]:
known_combined = pd.concat([df_1, df_2, df_3, df_4,df_5], ignore_index=True)
known_combined

,judul,BAB,Pasal,Content
0,PERMEN_BUMN_No_12_Tahun_2022_cleaned.txt,BAB I: KETENTUAN UMUM,PASAL 1,Dalam Peraturan Menteri ini yang dimaksud deng...
1,PERMEN_BUMN_No_12_Tahun_2022_cleaned.txt,BAB I: KETENTUAN UMUM,PASAL 2,Penata Kelola Per usahaan Negara berkedudukan...
2,PERMEN_BUMN_No_12_Tahun_2022_cleaned.txt,BAB I: KETENTUAN UMUM,PASAL 3,Pedoman perhitungan kebutuhan Jabatan Fungsion...
3,PERMEN_BUMN_No_12_Tahun_2022_cleaned.txt,BAB I: KETENTUAN UMUM,PASAL 4,(1) Jabatan Fu ngsional PKPN merupakan Jabat...
4,PERMEN_BUMN_No_12_Tahun_2022_cleaned.txt,BAB I: KETENTUAN UMUM,PASAL 5,Kualifikasi pendidikan untuk Jab atan Fungsion...
...,...,...,...,...
1349,PERMEN_BUMN_No_961_Tahun_2022_Merubah_958_2021...,"BAB II: dan BAB III disisipkan 1 (satu) BAB,",PASAL 5,iantara Pasal 4 dan Pasal 5 disisipkan 8 (del...
1350,PERMEN_BUMN_No_961_Tahun_2022_Merubah_958_2021...,"BAB II: dan BAB III disisipkan 1 (satu) BAB,",PASAL 6,(1) Sumber talenta berasal dari: a. Talenta ...
1351,PERMEN_BUMN_No_961_Tahun_2022_Merubah_958_2021...,"BAB II: dan BAB III disisipkan 1 (satu) BAB,",PASAL 7,(1) Talenta yang sudah dinominasikan sebagaima...
1352,PERMEN_BUMN_No_961_Tahun_2022_Merubah_958_2021...,"BAB II: dan BAB III disisipkan 1 (satu) BAB,",PASAL 13,(1) Sebelum dilakukan Uji Kelay akan dan Kepat...
1353,PERMEN_BUMN_No_961_Tahun_2022_Merubah_958_2021...,"BAB II: dan BAB III disisipkan 1 (satu) BAB,",PASAL 15,(1) Bagi kandidat yang diusulkan oleh Komite S...

In [8]:
unknown_combined.to_csv(r'C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\data\unknown_combined.csv', index=False, encoding='utf-8-sig')
known_combined.to_csv(r'C:\Users\Aqil Anhein\Desktop\TA\Peraturan Menteri\data\known_combined.csv', index=False, encoding='utf-8-sig')