In [1]:
import pandas as pd

In [36]:
doc = pd.read_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\doc(with dupes).xlsx")
bab = pd.read_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\bab(with dupes).xlsx")

In [37]:
doc

                             judul  judul_id    Label
0     PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
1     PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
2     PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
3     PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
4     PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
...                            ...       ...      ...
2950           UU No 40 Tahun 2007   1004007  DOKUMEN
2951           UU No 40 Tahun 2007   1004007  DOKUMEN
2952            UU No 6 Tahun 2023   1000623  DOKUMEN
2953            UU No 6 Tahun 2023   1000623  DOKUMEN
2954            UU No 8 Tahun 2016   1000816  DOKUMEN

[2955 rows x 3 columns]

In [38]:
bab

                              BAB     BAB_id Label
0           BAB I: KETENTUAN UMUM  200122201   BAB
1           BAB I: KETENTUAN UMUM  200122201   BAB
2           BAB I: KETENTUAN UMUM  200122201   BAB
3           BAB I: KETENTUAN UMUM  200122201   BAB
4           BAB I: KETENTUAN UMUM  200122201   BAB
...                           ...        ...   ...
2903  BAB XIII: KETENTUAN PENUTUP  100081613   BAB
2904  BAB XIII: KETENTUAN PENUTUP  100081613   BAB
2905  BAB XIII: KETENTUAN PENUTUP  100081613   BAB
2906  BAB XIII: KETENTUAN PENUTUP  100081613   BAB
2907  BAB XIII: KETENTUAN PENUTUP  100081613   BAB

[2908 rows x 3 columns]

In [39]:
doc_unique = doc.drop_duplicates(subset='judul_id')
bab_unique = bab.drop_duplicates(subset='BAB_id')

In [40]:
doc_unique

                               judul  judul_id    Label
0       PERMEN BUMN No 12 Tahun 2022   2001222  DOKUMEN
11    PERMEN BUMN No 1320 Tahun 2021   2132021  DOKUMEN
27    PERMEN BUMN No 1379 Tahun 2015   2137915  DOKUMEN
341   PERMEN BUMN No 1613 Tahun 2019   2161319  DOKUMEN
363    PERMEN BUMN No 176 Tahun 2022   2017622  DOKUMEN
395    PERMEN BUMN No 183 Tahun 2021   2018321  DOKUMEN
412    PERMEN BUMN No 251 Tahun 2021   2025121  DOKUMEN
554    PERMEN BUMN No 261 Tahun 2023   2026123  DOKUMEN
596    PERMEN BUMN No 262 Tahun 2023   2026223  DOKUMEN
827    PERMEN BUMN No 263 Tahun 2023   2026323  DOKUMEN
997    PERMEN BUMN No 340 Tahun 2020   2034023  DOKUMEN
1138   PERMEN BUMN No 438 Tahun 2021   2043821  DOKUMEN
1170   PERMEN BUMN No 473 Tahun 2018   2047318  DOKUMEN
1205   PERMEN BUMN No 576 Tahun 2022   2057622  DOKUMEN
1217   PERMEN BUMN No 784 Tahun 2020   2078420  DOKUMEN
1243   PERMEN BUMN No 815 Tahun 2021   2081521  DOKUMEN
1258   PERMEN BUMN No 835 Tahun 2022   2083522  DOKUMEN
1268   PERMEN BUMN No 934 Tahun 2021   2093421  DOKUMEN
1294  PERMEN BUMN No 958 Tahun 2021    2095821  DOKUMEN
1318   PERMEN BUMN No 961 Tahun 2022   2096122  DOKUMEN
1324             PP No 29 Tahun 2021   3002921  DOKUMEN
1503             PP No 33 Tahun 2005   3003305  DOKUMEN
1529              PP No 4 Tahun 2003   3000403  DOKUMEN
1535             PP No 34 Tahun 2021   3003421  DOKUMEN
1583             PP No 35 Tahun 2021   3003521  DOKUMEN
1590             PP No 36 Tahun 2021   3003621  DOKUMEN
1676             PP No 37 Tahun 2021   3003721  DOKUMEN
1726             PP No 50 Tahun 2012   3005012  DOKUMEN
1748             UU No 13 Tahun 2003   1001303  DOKUMEN
1938             UU No 14 Tahun 2019   1001419  DOKUMEN
2007             UU No 18 Tahun 2017   1001817  DOKUMEN
2098             UU No 19 Tahun 2003   1001903  DOKUMEN
2192             UU No 21 Tahun 2000   1002100  DOKUMEN
2239              UU No 2 Tahun 2004   1000204  DOKUMEN
2362             UU No 40 Tahun 2004   1004004  DOKUMEN
2415             UU No 40 Tahun 2007   1004007  DOKUMEN
2514              UU No 5 Tahun 1999   1000599  DOKUMEN
2538              UU No 8 Tahun 1999   1000899  DOKUMEN
2755  PERMEN BUMN No 1147 Tahun 2017   2114717  DOKUMEN
2770  PERMEN BUMN No 1196 Tahun 2019   2119619  DOKUMEN
2777  PERMEN BUMN No 1701 Tahun 2015   2170115  DOKUMEN
2780  PERMEN BUMN No 1702 Tahun 2015   2170215  DOKUMEN
2784  PERMEN BUMN No 1760 Tahun 2014   2176014  DOKUMEN
2788   PERMEN BUMN No 311 Tahun 2018   2031118  DOKUMEN
2793   PERMEN BUMN No 413 Tahun 2014   2041314  DOKUMEN
2797   PERMEN BUMN No 414 Tahun 2014   2041414  DOKUMEN
2814   PERMEN BUMN No 939 Tahun 2022   2093922  DOKUMEN
2839  PERMEN BUMN No 447 Tahun 2021    2044721  DOKUMEN
2841   PERMEN BUMN No 46 Tahun 2018    2004618  DOKUMEN
2851  PERMEN BUMN No 812 Tahun 2021    2081221  DOKUMEN
2855             PP No 41 Tahun 2003   3004103  DOKUMEN
2861             PP No 64 Tahun 2023   3006423  DOKUMEN
2887             PP No 19 Tahun 1973   3001973  DOKUMEN
2893             UU No 18 Tahun 2023   1001823  DOKUMEN
2906              UU No 1 Tahun 1970   1000170  DOKUMEN
2952              UU No 6 Tahun 2023   1000623  DOKUMEN
2954              UU No 8 Tahun 2016   1000816  DOKUMEN

In [41]:
bab_unique

                                                    BAB     BAB_id Label
0                                 BAB I: KETENTUAN UMUM  200122201   BAB
5          BAB II: PENYUSUNAN DAN PERHITUNGAN KEBUTUHAN  200122202   BAB
10                           BAB III: KETENTUAN PENUTUP  200122203   BAB
11                                BAB I: KETENTUAN UMUM  213202101   BAB
13    BAB II: PENGANGKATAN DALAM JABATAN FUNGSIONAL ...  213202102   BAB
...                                                 ...        ...   ...
2892                                BAB IX: PENGHARGAAN  100081609   BAB
2896                                    BAB X: LARANGAN  100081610   BAB
2898                           BAB XI: KETENTUAN PIDANA  100081611   BAB
2900                       BAB XII: KETENTUAN PERALIHAN  100081612   BAB
2902                        BAB XIII: KETENTUAN PENUTUP  100081613   BAB

[367 rows x 3 columns]

In [42]:
doc_unique.to_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\doc.xlsx", index=False)
bab_unique.to_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\bab.xlsx", index=False)

In [29]:
doc_bab = pd.read_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\rels\doc_bab(with dupes).xlsx")
doc_pasal = pd.read_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\rels\doc_pasal.xlsx")

In [20]:
doc_bab

      Start_id     End_id      Type
0      2001222  200122201  CONTAINS
1      2001222  200122201  CONTAINS
2      2001222  200122201  CONTAINS
3      2001222  200122201  CONTAINS
4      2001222  200122201  CONTAINS
...        ...        ...       ...
2750   1000899  100089913  CONTAINS
2751   1000899  100089913  CONTAINS
2752   1000899  100089913  CONTAINS
2753   1000899  100089913  CONTAINS
2754   1000899  100089913  CONTAINS

[2755 rows x 3 columns]

In [22]:
doc_bab_unique = doc_bab.drop_duplicates(subset=['Start_id', 'End_id'], keep='first')
doc_pasal_unique = doc_pasal.drop_duplicates(subset=['Start_id', 'End_id'], keep='first')
doc_bab

      Start_id     End_id      Type
0      2001222  200122201  CONTAINS
1      2001222  200122201  CONTAINS
2      2001222  200122201  CONTAINS
3      2001222  200122201  CONTAINS
4      2001222  200122201  CONTAINS
...        ...        ...       ...
2750   1000899  100089913  CONTAINS
2751   1000899  100089913  CONTAINS
2752   1000899  100089913  CONTAINS
2753   1000899  100089913  CONTAINS
2754   1000899  100089913  CONTAINS

[2755 rows x 3 columns]

In [31]:
doc_bab_unique.to_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\rels\doc_bab_unique.xlsx", index=False)

In [60]:
prev = pd.read_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\rels\prev.xlsx")
prev

          Start_id
0     200122201001
1     200122201002
2     200122201003
3     200122201004
4     200122201005
...            ...
2934  100400700060
2935  100400700061
2936  100400700062
2937  100062300001
2938  100062300002

[2939 rows x 1 columns]

In [61]:
# 1. Remove rows where Start_id % 10 == 1
prev = prev[prev['Start_id'] % 1000 != 1].copy()

# 2. Add column End_id = Start_id - 1
prev['End_id'] = prev['Start_id'] - 1

# 3. Add column that checks if Start_id - End_id == 1
prev['Relation'] = prev.apply(lambda x: 'PREV' if x['Start_id'] - x['End_id'] == 1 else None, axis=1)

# 4. Keep only rows where Relation == 'PREV'
prev = prev[prev['Relation'] == 'PREV'].reset_index(drop=True)
prev

          Start_id        End_id Relation
0     200122201002  200122201001     PREV
1     200122201003  200122201002     PREV
2     200122201004  200122201003     PREV
3     200122201005  200122201004     PREV
4     200122202006  200122202005     PREV
...            ...           ...      ...
2882  100400700059  100400700058     PREV
2883  100400700060  100400700059     PREV
2884  100400700061  100400700060     PREV
2885  100400700062  100400700061     PREV
2886  100062300002  100062300001     PREV

[2887 rows x 3 columns]

In [62]:
prev.to_excel(r"C:\Users\Aqil Anhein\Desktop\TA\md\rels\prev_fixed.xlsx", index=False)